In [1]:
print("Hello world")

Hello world


In [3]:
import numpy as np

In [4]:
a = np.array([1 , 2 , 3 ,4 , 5])

In [5]:
x = a.view()
x[0] = 100

In [6]:
print(a)
print(x)

[100   2   3   4   5]
[100   2   3   4   5]


In [7]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)


[[1 2 3]
 [4 5 6]]


In [10]:
from numpy import random
x = random.randint(100, size=(3, 5))
print(x)

[[42 87 27 16 63]
 [28 78 22  1 53]
 [41 15 81 68 91]]


In [13]:
x = random.rand(3 , 2)
print(x)

[[0.78076359 0.16477767]
 [0.20302595 0.39028278]
 [0.83297447 0.24513978]]


In [14]:
y = random.choice([1  ,2 , 3, 4, 5])
print(y)

2


In [1]:
import numpy as np

In [3]:
a = np.array([1 , 2, 3 , 4 ,5])

b = np.array([6, 7, 8, 9, 10])

print(a+b)

[ 7  9 11 13 15]


In [4]:
b = np.array([[1, 2 , 3] , [4 , 5 , 6]])

print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(b.ndim)

2


In [7]:
print(b.shape)  #shape gives the number of rows and cooums like dimensions of what order

(2, 3)


In [9]:
print(b.size)  #size gives total elements

6


In [10]:
print(b.dtype)

int64


In [11]:
c = np.array([1 , 2.1 , 3])

print(c)

print(c.dtype)

[1.  2.1 3. ]
float64


In [12]:
d = np.array([1 , 2 , 3, 4] , dtype = float)
print(d)

[1. 2. 3. 4.]


In [15]:
a = (np.zeros(6))
print(a)

[0. 0. 0. 0. 0. 0.]


In [17]:
d = np.zeros((2 , 3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
e = np.ones((3 , 4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
d = np.full((3 , 4) , 8)
print(d)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [24]:
print(np.arange(0, 10, 2))

[0 2 4 6 8]


In [26]:
k = np.linspace(0 , 1 , 6)
print(k)

[0.  0.2 0.4 0.6 0.8 1. ]


In [27]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(b[0, :])

[1 2 3]


In [28]:
print(b[:, 1])

[2 5 8]


In [29]:
print(b[0:2, 1:3])

[[2 3]
 [5 6]]


In [30]:
b = np.array([[1, 2],
              [3, 4]])
b[0, 1] = 100
print(b)

[[  1 100]
 [  3   4]]


In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [32]:
print(a + b)

[5 7 9]


In [33]:
print(a-b)

[-3 -3 -3]


In [34]:
print(a*b)

[ 4 10 18]


In [35]:
print(a/b)

[0.25 0.4  0.5 ]


In [36]:
print(a**2)

[1 4 9]


In [37]:
a = np.array([1 , 2 , 3])

print(a+10)

[11 12 13]


In [38]:
print(a*2)

[2 4 6]


In [39]:
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))

6
2.0
1
3
0.816496580927726


In [40]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print(b.sum())

21


In [ ]:
print(b.sum(axis = 0))  #0 used for coloum sum

[5 7 9]


In [43]:
print(b.sum(axis = 1))

[ 6 15]


In [44]:
a = np.array([1, 2, 3, 4, 5, 6])

In [45]:
b = a.reshape(2 ,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [46]:
c = a.reshape(3 , 2)

In [47]:
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [48]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print(b.flatten())

[1 2 3 4 5 6]


In [51]:
print(np.random.rand(3))

[0.09674285 0.12200162 0.66113133]


In [52]:
print(np.random.rand(2, 3))

[[0.61136119 0.8158472  0.87754735]
 [0.6769215  0.60268028 0.87526597]]


In [53]:
print(np.random.randint(1, 10, size=5))

[6 2 7 3 7]


In [54]:
print(a[a>25])

[]


In [55]:
a = np.array([1, 2, 3, 4])
b = a
b[0] = 100

print(a)
print(b)

[100   2   3   4]
[100   2   3   4]


In [56]:
a = np.array([1, 2, 3, 4])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3 4]
[100   2   3   4]


In [57]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.concatenate((a, b)))

[1 2 3 4 5 6]


In [58]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]


In [59]:
print(np.hstack((a, b)))

[1 2 3 4 5 6]


In [60]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

print(a * b)

[[ 5 12]
 [21 32]]


In [61]:
print(a @ b)

[[19 22]
 [43 50]]


In [62]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

print(a + b)

[[11 22 33]
 [14 25 36]]


In [63]:
a = np.array([1, 4, 9, 16])
print(np.sqrt(a))

[1. 2. 3. 4.]


In [64]:
b = np.array([[3, 1, 2],
              [6, 5, 4]])
print(np.sort(b))

[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([10, 20, 30, 20])

print(np.where(a == 20))

(array([1, 3]),)


In [66]:
marks = np.array([72, 85, 90, 66, 58, 77])

print("Average:", marks.mean())
print("Highest:", marks.max())
print("Passed:", marks[marks >= 60])

Average: 74.66666666666667
Highest: 90
Passed: [72 85 90 66 77]


In [ ]:
import numpy as np

np.array([1,2,3])           # create array
np.zeros((2,3))             # zeros
np.ones((2,2))              # ones
np.arange(0,10,2)           # range array
np.linspace(0,1,5)          # evenly spaced

a.shape                     # shape
a.ndim                      # dimensions
a.size                      # number of elements
a.dtype                     # data type

a[0]                        # first element
a[1:4]                      # slice
a[:,1]                      # column
a[0,:]                      # row

a + b                       # add
a * b                       # element-wise multiply
a @ b                       # matrix multiply

a.sum()
a.mean()
a.max()
a.min()

a.reshape(2,3)              # reshape
a.flatten()                 # make 1D

a[a > 5]                    # filtering

In [71]:
import numpy as np

a = np.arange(5 , 25 , 5)
print(a)

[ 5 10 15 20]


In [72]:
a = a+3
print(a)

[ 8 13 18 23]


In [73]:
a = a*2

In [74]:
print(a)

[16 26 36 46]


In [75]:
print(np.mean(a))

31.0


In [76]:
print(a[a>10])

[16 26 36 46]


In [81]:

a = np.arange(1, 7).reshape(2, 3)

print(a)

[[1 2 3]
 [4 5 6]]


In [82]:
print(a[1:2 , : ])

[[4 5 6]]


In [83]:
print(a[: , 2:3])

[[3]
 [6]]


In [84]:
d = np.array([1 , 2 , 3, 4 , 5 , 6 , 7 , 8])
print(d.reshape(2 , 4))

[[1 2 3 4]
 [5 6 7 8]]


In [85]:
a = np.array([[1, 2] , [3 ,4]])
b = np.array([[5 , 6] , [7 ,8]])

print(a@b)

[[19 22]
 [43 50]]


In [86]:


a = np.array([12, 5, 18, 7, 20, 3, 15, 9, 22, 11])

In [87]:
print(a[a>10])

[12 18 20 15 22 11]


In [88]:
print(a[a%2==0])

[12 18 20 22]


In [89]:
print(np.mean(a[a>10]))

16.333333333333332


In [91]:
a[a<10] = -1
print(a)

[12 -1 18 -1 20 -1 15 -1 22 11]


In [97]:
import numpy as np

a = np.array([12, 5, 18, 7, 20, 3, 15, 9, 22, 11])

indices = np.where(a > 15)
print(indices)

(array([2, 4, 8]),)


In [98]:
b = np.array([[4, 7, 2],
              [9, 1, 5],
              [6, 8, 3]])

In [99]:
print(b[1:2 , :])

[[9 1 5]]


In [102]:
print(b[: , 2:3])

[[2]
 [5]
 [3]]


In [103]:
print(b.sum(axis = 1))

[13 15 17]


In [104]:
print(b.sum(axis = 0))

[19 16 10]


In [105]:
print(np.max(b))

9


In [106]:
print(np.where(b==np.max(b)))

(array([1]), array([0]))


In [107]:
b[b<5] = 0
print(b)

[[0 7 0]
 [9 0 5]
 [6 8 0]]


In [108]:
c = np.arange(1, 13)

In [109]:
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [114]:
c = c.reshape(3 , 4)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [115]:
v = np.array([10, 20, 30, 40])

In [118]:
d = (c+v)
print(d)

[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


In [119]:
c_t = c.T
print(c_t)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [120]:
print(c@c_t)

[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [123]:
print(c.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [2]:
print("Hello world")

Hello world
